apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-cleaner.fullname" . }}
  labels:
    {{- include "k8s-cleaner.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: {{ .Values.service.healthzPort }}
      targetPort: healthz
      protocol: TCP
      name: healthz
  selector:
    {{- include "k8s-cleaner.selectorLabels" . | nindent 4 }}
  {{- with .Values.service.sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}
